name: Build Specific Sample
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # CHANGE THIS to the folder name of the sample you want
    defaults:
      run:
        working-directory: ./JetNews

    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x ../gradlew # Points to gradlew in the root
        
      - name: Build Debug APK
        # We call the root gradlew but tell it to build this specific project
        run: ../gradlew assembleDebug 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sample-apk
          # Matches the path where Gradle puts the output
          path: ./**/build/outputs/apk/debug/*.apk
